sudo: required
language: generic

services:
  - docker


before_install:
  - docker build -t k-nesterov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true k-nesterov/docker-react npm run test
